version: '3'

services:
  mininet:
    image: opennetworking/mininet
    privileged: true
    tty: true
    container_name: mininet
    command: /bin/bash
    ports:
      - "6633:6633"  # Puerto OpenFlow
      - "6653:6653"  # Puerto OpenFlow (versión 1.3)
      - "6640:6640"  # Puerto OpenFlow (versión 1.0)
      - "6655:6655"  # Puerto Ryu
    networks:
      mininet-net:
        ipv4_address: 10.0.0.2

  opendaylight:
    image: opendaylight/odl:latest
    container_name: opendaylight
    ports:
      - "8181:8181"  # Puerto web de OpenDaylight
      - "8101:8101"  # Puerto de la consola Karaf
    networks:
      mininet-net:
        ipv4_address: 10.0.0.3
    environment:
      KARAF_NAME: opendaylight
      KARAF_HOME: /opt/opendaylight
      JAVA_MAX_MEM: 2048M
      JAVA_MIN_MEM: 1024M
      EXTRA_JAVA_OPTS: "-XX:MaxPermSize=256m"

  ryu:
    image: osrg/ryu
    container_name: ryu
    ports:
      - "6633:6633"  # Puerto OpenFlow (usado por Ryu)
    networks:
      mininet-net:
        ipv4_address: 10.0.0.4

networks:
  mininet-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
